# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: System identification of Vessel Manoeuvring Models
author: Martin Alexandersson
logo: logo.png

only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/martinlarsalbert/wPCC_pipeline  # Online location of your book
  path_to_book: docs/paper  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true


sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js  # To enable plotly plot
    #mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  # Faster math?
    latex_engine: xelatex
    latex_elements:
      papersize: ""
      fontpkg: ""
      fncychap: ""
      maketitle: ""
      pointsize: ""
      preamble: ""
      releasename: ""
      babel: ""
      printindex: ""
      fontenc: ""
      inputenc: ""
      classoptions: ""
      utf8extra: ""
      maketitle: ""
      tableofcontents: ""

  extra_extensions:
    - sphinx_proof
  

#parse:
#  myst_enable_extensions:
#    # don't forget to list any other extensions you want enabled,
#    # including those that are enabled by default!
#    - amsmath
#
#sphinx:
#  config:
#    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
