"""
This is a boilerplate pipeline 'kvlcc2'
generated using Kedro 0.17.6
"""

import pandas as pd
import numpy as np
from src.prime_system import PrimeSystem


def load(df: pd.DataFrame, ship_data: dict) -> pd.DataFrame:
    """load kvlcc2 data and transform it

    Parameters
    ----------
    df : pd.DataFrame
        kvlcc2 data

    Returns
    -------
    pd.DataFrame
        With correct column naming and radians etc.
    """

    df.dropna(how="all", inplace=True)

    scale_factor = ship_data["scale_factor"]

    dt = 0.135 / np.sqrt(scale_factor)
    df["time"] = np.arange(0, len(df) * dt, dt)

    df.set_index("time", inplace=True)
    df.sort_index(inplace=True)
    angles = ["phi", "psi", "r", "delta"]
    df[angles] = np.deg2rad(df[angles])

    ## To model scale:
    df["x0"] /= scale_factor
    df["y0"] /= scale_factor
    df["u"] /= np.sqrt(scale_factor)
    df["v"] /= np.sqrt(scale_factor)
    df["p"] *= np.sqrt(scale_factor)
    df["r"] *= np.sqrt(scale_factor)
    df["rev"] *= 1 / 60 * np.sqrt(scale_factor)  # [rps]
    df["thrust"] = 0  # not true...
    df["V"] = np.sqrt(df["u"] ** 2 + df["v"] ** 2)

    return df


def calculate_thrust(
    df: pd.DataFrame,
    ship_data: dict,
    open_water_characteristics: pd.DataFrame,
) -> pd.DataFrame:

    u = df["u"]
    v = df["v"]
    r = df["r"]

    n = df["rev"]
    D = ship_data["D"]

    """
    Yasukawa, H., Yoshimura, Y., 2015. Introduction of MMG standard method for ship maneuvering predictions. J Mar Sci Technol 20, 37–52. https://doi.org/10.1007/s00773-014-0293-y
    """

    beta = -np.arctan2(v, u)

    ps = PrimeSystem(**ship_data)
    xp_prime = ps._prime(
        ship_data["X_rudder"],
        unit="length",
    )
    r_prime = ps._prime(r, unit="angular_velocity", U=df["V"])
    beta_p = beta - xp_prime * r_prime

    w0 = ship_data["w0"]
    C_1 = ship_data["C_1"]
    C_2 = np.where(beta_p > 0, ship_data["C_2_beta_p_pos"], ship_data["C_2_beta_p_neg"])
    w = 1 - (1 - w0) * (1 + (1 - np.exp(-C_1 * np.abs(beta_p))) * (C_2 - 1))
    J = u * (1 - w) / (n * D)

    """
    Dai, K., Li, Y., 2019. Manoeuvring Prediction of KVLCC2 with Hydrodynamic Derivatives Generated by a Virtual Captive Model Test. Polish Maritime Research 26, 16–26. https://doi.org/10.2478/pomr-2019-0062
    """

    coefficients = np.polyfit(
        x=open_water_characteristics.index, y=open_water_characteristics["Kt"], deg=2
    )
    Kt = np.polyval(p=coefficients, x=J)
    rho = ship_data["rho"]
    df["thrust"] = rho * n ** 2 * D ** 4 * Kt

    return df
